<?php
namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * 重置静态资源版本（清除浏览器cache）
 *
 * Class AssetsReset
 * @package App\Console\Commands
 */
class AssetsReset extends Command
{
    const ENV_KEY = 'ASSET_VERSION';

    protected
        $current_asset_version = 0;
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $name = 'assets:reset';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Reset assets browser cache';

    /**
     * Create a new command instance.
     */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub

        $this->current_asset_version = env(self::ENV_KEY, date('Ymd'));

    }


    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $path = base_path('.env');

        $new_version = date('Ymd');
        if (is_numeric($this->current_asset_version)) {
            $new_version = $this->current_asset_version + 1;
        }

        if (file_exists($path)) {
            file_put_contents($path, str_replace(
                self::ENV_KEY.'='.$this->current_asset_version, self::ENV_KEY.'='.$new_version, file_get_contents($path)
            ));

            $this->info("Assets version has been reset successfully.");
        }
    }
}
